name: social_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.0.4
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  sqflite: ^2.0.3
  shared_preferences: ^2.0.15
  responsive_builder: ^0.4.2
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  freezed: ^2.0.3


flutter_intl:
  enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

